### ISSUE TITLE
Feedback for the Basisfuncties (Desktop) - 05.09.24

### ISSUE THREAD

**Issue by EkaterinaCoumans** [teamforus/forus-website#16]
I've noticed that the page isn't fully opening; the home page is still visible in the background.

<img width="1494" alt="Screenshot 2024-09-05 at 15 50 18" src="https://github.com/user-attachments/assets/bf102bb0-d822-471b-b4c6-5156d4c44192">

Additionally, the floating text from the home page appears on the 'About Us' page when you scroll down.

<img width="1465" alt="Screenshot 2024-09-05 at 15 49 34" src="https://github.com/user-attachments/assets/90ebff51-4ce3-4874-b33d-26185bfa9ae7">

**Comment by MariaForus** [comment]
@EkaterinaCoumans thanks! That's really weird. On my laptop, I can't even scroll when I'm opening the navigation bar, but it seems like you can still scroll on the page in the background. 

@aghimpu can you please take a loot at this? Any idea why it's happening? We need to definitely fix it before going live
