### ISSUE TITLE
Feedback for the About us (Desktop) - 05.09.24

### ISSUE THREAD

**Issue by EkaterinaCoumans** [teamforus/forus-website#17]
I've noticed that the page isn't fully opening; the home page is still visible in the background.

<img width="1499" alt="Screenshot 2024-09-05 at 15 50 49" src="https://github.com/user-attachments/assets/39bce704-8647-42ef-8c11-9a3fb0cdd2c5">

Additionally, the floating text from the home page appears on the 'About Us' page when you scroll down.

<img width="1501" alt="Screenshot 2024-09-05 at 16 00 27" src="https://github.com/user-attachments/assets/259ca674-57dd-46bb-869c-8926fcdc928e">

**Comment by aghimpu** [comment]
It's basically the same issue as https://github.com/teamforus/forus-website/issues/16. I've fixed it on all pages, so I would close this one and keep just https://github.com/teamforus/forus-website/issues/16 until it's verified and approved.
