### ISSUE TITLE
Feedback website - Contact form demo page

### ISSUE THREAD

**Issue by LindaForus** [teamforus/forus-website#18]
## Feedback

- [ ] Contactpage - Contactform - It is not clear that people can click on the word "Privacyverklaring". Make it visually clear that this is a link by adding styling to the link text.
![Scherm­afbeelding 2024-09-05 om 16 09 38](https://github.com/user-attachments/assets/f4f2f0d3-05cc-44d7-90e4-538c43d2316f)

**Comment by aghimpu** [comment]
I've made that text underlined for now, will this do it? If not @sashooa please provide a Figma update.

**Comment by LindaForus** [comment]
@aghimpu Thx, for me this will work! @sashooa What do you think?

**Comment by MariaForus** [comment]
@aghimpu can you please adjust it also for the Demo page?

**Comment by lexlog** [comment]
sprint status - @aghimpu it's done
closing issue
