### ISSUE TITLE
Maria | Website feedback 09.09 

### ISSUE THREAD

**Issue by MariaForus** [teamforus/forus-website#22]
### Homepage - Unique aspects

**Hulp en ondersteuning**

- [ ] Onze klantenservice staat open voor alle gebruikersvragen. Ons team van experts is beschikbaar om assistentie te verlenen waar nodig. U kunt hulp aanvragen via chat, telefoon of e-mail. Als we een oproep missen, dan bellen **we** altijd terug.

There was a word "we" missing in the text. @aghimpu can you please adjust it?

**Comment by lexlog** [comment]
done
