### ISSUE TITLE
Missing webpage 404 (Me-app download page)

### ISSUE THREAD

**Issue by MichaelForus** [teamforus/forus-website#24]
The webpage: https://forus.io/dl is missing on our website. 
This results in a 404 error message.

The Me-app can be downloaded on this page, and we use this URL a lot on webshops and Helpcenter articles.

Example:
<img width="1033" alt="Scherm­afbeelding 2024-09-11 om 13 15 38" src="https://github.com/user-attachments/assets/fda36e6d-2ed6-4494-af88-da54373201ab">

**Comment by lexlog** [comment]
before it was a page which supposed to redirect user to the correct app store according to OS used
https://dev.forus.io/#!/DL
(but I was not able to see it works as from iOS as from Android)

**Comment by LindaForus** [comment]
Notes of meeting

**Comment by LindaForus** [comment]
@sashooa Could you please make the same/similar design for the new website?
- Link to old page: https://dev.forus.io/#!/DL
- Use the same text as on the old page
- Add the new download buttons
- Add the navigation to the page

Clarity: 8/10
Estimations: 1-2h
Planning: tomorrow around 2.30pm

**Comment by sashooa** [comment]
@lexlog Here we go with a ✅ **Master** file from **Figma**: https://www.figma.com/design/cDtBUMIdHalpMLUKlLCklM/Missing-webpage-404-(Me-app-download-page)-%2324?node-id=1-2

**Comment by LindaForus** [comment]
@aghimpu Could you please check the design (master file in Figma), see link in comment above.

Scope for the page:
- add title and subtitle
- add 2 download buttons: Android and iOS (+ hovers)
- add the general menu of the website
- add the general footer of the website
- How the page should work:
  - If possible the link will go directly to the right app store and download page of Me-app. 
  - If this is not possible, the page will be visible and the user can click on the button to go to the desired app store.

**Comment by aghimpu** [comment]
Done https://github.com/teamforus/forus-frontend-react/pull/281/commits/75cade4cd36085657b86abb7f9776129a993ccbc

**Comment by LindaForus** [comment]
@aghimpu Thanks! 

@lexlog The page is developed. Could you schedule this issue for review and release?

**Comment by lexlog** [comment]
@LindaForus hey, I deployed this page yesterday on prod in case of urgency and more simple release process
in terms of testing - it works for Android and didn't work for iOS for me, so I will proceed today with it to check
